// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo2799LeBzf1Hcf1mC_03fJq0SkT8e3Vk',
    appId: '1:474176014039:web:b30cc0572957dfc41f9292',
    messagingSenderId: '474176014039',
    projectId: 'seguros-desafio',
    authDomain: 'seguros-desafio.firebaseapp.com',
    storageBucket: 'seguros-desafio.firebasestorage.app',
    measurementId: 'G-35QC8531SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJzEz_b6pE3Vzx-aj58DDpHSamR1Mes7M',
    appId: '1:474176014039:android:015e4efc8bc71a2b1f9292',
    messagingSenderId: '474176014039',
    projectId: 'seguros-desafio',
    storageBucket: 'seguros-desafio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNYolbAbHpjJdvkPBw25lUlrObzeZrbqE',
    appId: '1:474176014039:ios:1de716bba0049d3a1f9292',
    messagingSenderId: '474176014039',
    projectId: 'seguros-desafio',
    storageBucket: 'seguros-desafio.firebasestorage.app',
    iosBundleId: 'com.velvet.eclipse.waterReminder',
  );
}
